# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
################################################################################
#
# Ansible Default Variables
#
# This file contains the default values for variables used in the Ansible
# playbooks. These variables can be overridden by defining them in the
# gcp_oracle.yml file.
#
################################################################################


################################################################################
# Software installation & environment
################################################################################

free_edition: "{{ oracle_edition == 'FREE' }}"
gi_install: "{{ not free_edition and not ora_disk_management == 'fs' }}"
swlib_path: "{{ ora_swlib_path | lower | default(swlib_path_default,true) }}"
swlib_unzip_path: "{{ ora_staging | lower | default(swlib_path,true) }}"
swlib_mount_type: "{{ ora_swlib_type | lower | default('gcs',true) }}"
swlib_mount_src: "{{ ora_swlib_bucket | default('',true) | regex_replace ('^gs://') }}"
swlib_gcs_service_account_file: "{{ ora_swlib_credentials | default('',true) }}"
swlib_path_default: "{{ oracle_user_data_mounts | selectattr('purpose', 'match', '^software$') | map(attribute='mount_point') | list | first }}/swlib"
swap_blk_device: "{{ swap_blk_device | lower | default('',true) }}"
ntp_preferred: "{{ ntp_pref | lower | default('',true) }}"
db_password_secret: "{{ db_password_secret | lower | default('',true) }}"
oracle_root: "/u01/app"
home_name: "{% if free_edition %}dbhomeFree{% else %}dbhome_1{% endif %}"
create_db: true
create_listener: true
install_rdbms: true


################################################################################
# User and group settings
################################################################################

oracle_user: oracle
oracle_group: oinstall
grid_user: "{% if role_separation %}grid{% else %}{{ oracle_user }}{% endif %}"
grid_group: asmadmin


################################################################################
# SSH settings
################################################################################

ansible_ssh_user: "{{ instance_ssh_user }}"
ansible_ssh_private_key_file: "{{ instance_ssh_key }}"
ansible_ssh_common_args: "{{ instance_ssh_extra_args | default('', true) }}"
firsttime_connect_user: "customeradmin"
control_node_key_file: "~/.ssh/id_rsa_oracle_toolkit"


################################################################################
# Database configuration
################################################################################

db_name: "{{ ora_db_name | default('ORCL',true) }}"
db_domain: "{{ ora_db_domain | default('',true) }}"
oracle_ver: >-
  {% set version_map = {
    '23': '23.0.0.0.0',
    '21': '21.3.0.0.0',
    '19': '19.3.0.0.0',
    '18': '18.0.0.0.0',
    '12': '12.2.0.1.0',
    '12.2': '12.2.0.1.0',
    '12.1': '12.1.0.2.0',
    '11': '11.2.0.4.0'
  } %}{{ version_map[ora_version | string] | default(ora_version, true) | default('19.3.0.0.0',true) }}
oracle_ver_base: "{{ oracle_ver | regex_replace('^(.*?\..*?)\..*$', '\\1') }}"
oracle_rel: "{{ ora_release | default('latest',true) }}"
oracle_edition: "{{ ora_edition | default('EE',true) }}"
cluster_type: "{{ cluster_type | default('NONE',true) }}"
container_db: "{{ ora_db_container | default(false,true) | bool }}"
pdb_prefix: "{{ ora_pdb_name_prefix | default('PDB',true) }}"
pdb_count: "{{ ora_pdb_count | default('1',true) }}"
db_type: "{{ ora_db_type | lower | default('multipurpose',true) }}"
redologsize: "{{ ora_redo_log_size | regex_replace('^(.*)MB$', '\\1') | default('100',true) }}"
charset: "{{ ora_db_charset | default('AL32UTF8',true) }}"
ncharset: "{{ ora_db_ncharset | default('AL16UTF16',true) }}"
db_config_type: "{% if cluster_type | default('NONE', true) in ('NONE', 'DG') %}SI{% elif cluster_type == 'RAC' %}RAC{% endif %}"
instance_num: 1
memory_pct: 45
ora_pga_target_mb: "{{ ora_pga_target_mb | int | default('150',true) }}"
ora_sga_target_mb: "{{ ora_sga_target_mb | int | default((ansible_memory_mb.real.total*memory_pct)//100,true) }}"
oracle_sid: "{% if db_config_type == 'SI' %}{{ db_name }}{% else %}{{ db_name }}{{ instance_num }}{% endif %}"


################################################################################
# ASM and storage
################################################################################

ora_disk_management: "{{ ora_disk_mgmt | lower | default('udev',true) }}"
role_separation: "{{ ora_role_separation | default('true', true) | lower | bool }}"
data_destination: "{{ ora_data_destination | default('DATA',true) }}"
reco_destination: "{{ ora_reco_destination | default('RECO',true) }}"
use_omf: true
oracle_user_data_mounts_default:
  - { purpose: software, blk_device: /dev/BOGUS, fstype: xfs, mount_point: /u01, mount_opts: "nofail" }
  - { purpose: diag, blk_device: /dev/BOGUS, fstype: xfs, mount_point: /u02, mount_opts: "nofail" }
data_mounts_definition_file: "{{ ora_data_mounts | default('data_mounts_config.json',true) }}"
data_mounts_input: "{{ lookup('file', ora_data_mounts, errors='ignore') if ora_data_mounts is defined else ora_data_mounts_json }}"
oracle_user_data_mounts: "{{ data_mounts_input | default(oracle_user_data_mounts_default,true) }}"
asm_disks_default:
  - diskgroup: "{{ data_destination }}"
    disks:
      - name: DATA1
        blk_device: /dev/BOGUS
  - diskgroup: "{{ reco_destination }}"
    disks:
      - name: RECO1
        blk_device: /dev/BOGUS
  - diskgroup: DEMO
    disks:
      - name: DEMO1
        blk_device: /dev/BOGUS
asm_definition_file: "{{ ora_asm_disks | default('asm_disk_config.json',true) }}"
asm_disk_input: "{{ lookup('file',asm_definition_file,errors='ignore') }}"
asm_disks: "{% if gi_install %}{{ asm_disk_input | default(asm_disks_default,true) }}{% else %}[]{% endif %}"
asm_sid: "{% if db_config_type == 'SI' %}+ASM{% else %}+ASM{{ instance_num }}{% endif %}"
u01_lun: "{{ ora_u01_lun | lower | default('',true) }}"


################################################################################
# Oracle listener configuration
################################################################################

listener_port: "{{ ora_listener_port | default('1521',true) }}"
listener_name: "{{ ora_listener_name | default('LISTENER',true) }}"


################################################################################
# Backup and recovery configuration
################################################################################

scripts_dir: "/home/{{ oracle_user }}/scripts"
logs_dir: "/home/{{ oracle_user }}/logs"
backup_dest: "{{ backup_dest }}"
gcsfuse_backup_config: "{{ gcs_backup_config | lower | default('',true) }}"
gcsfuse_backup_bucket: "{{ gcs_backup_bucket | default('',true) | regex_replace('^gs://([^/]+).*$', '\\1') }}"
gcsfuse_backup_bucket_folder: "{{ gcs_backup_bucket | default('',true) | regex_replace('^gs://[^/]+/?|/$', '') }}"
gcsfuse_backup_temp_path: "{{ gcs_backup_temp_path | default('',true) }}"
gcsfuse_backup_path: "{{ gcs_backup_path | default('',true) }}"
gcsfuse_backup_mount_path: "{{ backup_dest | default('',true) }}"
nfs_backup_config: "{{ nfs_backup_config | regex_replace('^nfsv','vers=') }}"
nfs_backup_mount: "{{ nfs_backup_mount }}"
rman_db_bu_redundancy: "{{ backup_redundancy | default('2',true) }}"
rman_arch_redundancy: "{{ archive_redundancy | default('2',true) }}"
rman_archs_online_days: "{{ archive_online_days | default('7',true) }}"
full_bu_level0_day: "{{ backup_level0_days | default('0',true) }}"
full_bu_level1_days: "{{ backup_level1_days | default('1-6',true) }}"
full_bu_start_hour: "{{ backup_start_hour | default('01',true) }}"
full_bu_start_min: "{{ backup_start_min | default('00',true) }}"
arch_bu_start_min: "{{ archive_backup_min | default('30',true) }}"
run_initial_bu: true


################################################################################
# Google Cloud Workload Agent settings
################################################################################

install_workload_agent: "{{ install_workload_agent | lower | default(false) }}"
oracle_metrics_secret: "{{ oracle_metrics_secret | lower | default('', true)}}"


################################################################################
# Oracle Data Guard configuration
################################################################################

real_time_apply: true
data_guard_protection_mode: "{{ data_guard_protection_mode | lower | default('Maximum Availability', true)}}"
log_transport_mode: "{{ 'ASYNC' if data_guard_protection_mode | upper == 'MAXIMUM PERFORMANCE' else 'SYNC' }}"


################################################################################
# Server configuration
################################################################################

disable_firewall: false
proxy_setup: "{{ ora_proxy_setup | lower | default('false',true) }}"


################################################################################
# System requirements
################################################################################

minimum_ansible_version: 2.9
os_supported_architecture: "x86_64"
os_family_supported: "RedHat"
os_min_supported_version: "{% if free_edition %}8{% else %}7.3{% endif %}"
os_minimum_memory_mb: 2560
os_minimum_swap_mb: 8192
