## Customizable Global Variables

# Installation related variables:

oracle_user_data_mounts:
  - { purpose: software, blk_device: /dev/sdb, fstype: xfs, mount_point: /u01, mount_opts: "defaults" }
  - { purpose: other, blk_device: /dev/sdc, fstype: xfs, mount_point: /u02, mount_opts: "defaults" }

asm_disks:
- diskgroup: "{{ data_diskgroup }}"
  disks:
  - name: DATA1
    blk_device: /dev/sdd
- diskgroup: "{{ reco_diskgroup }}"
  disks:
  - name: RECO1
    blk_device: /dev/sde
- diskgroup: DEMO
  disks:
  - name: DEMO1
    blk_device: /dev/sdf
