# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: Execute SQL query to get DBID
  ansible.builtin.shell: |
    set -o pipefail
    sqlplus -s / as sysdba <<EOF
    SET HEADING OFF
    SET FEEDBACK OFF
    SET LINESIZE 999
    SET PAGESIZE 0
    SET TRIMSPOOL ON
    SELECT dbid FROM v\$database;
    EXIT;
    EOF
  environment:
    ORACLE_HOME: "{{ oracle_home }}"
    ORACLE_SID: "{{ oracle_sid }}"
    PATH: "{{ oracle_home }}/bin:{{ ansible_env.PATH }}"
  register: dbid_query_result
  changed_when: false

- name: Extract DBID and handle errors
  ansible.builtin.set_fact:
    oracle_dbid: "{{ dbid_query_result.stdout | trim if 'ORA-' not in dbid_query_result.stderr else '' }}"
    oracle_error_output: "{{ dbid_query_result.stderr | default('') }}"

- name: Output DBID or error
  ansible.builtin.debug:
    msg: "{{ oracle_dbid if oracle_dbid else oracle_error_output | trim }}"
    verbosity: 0
