# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
- name: swap | Create swap partition
  parted:
    device: "{{ swap_blk_device }}"
    number: 1
    state: present
  become: true
  register: swapfile_register_create

- name: Collect new disk facts
  setup:
    gather_subset:
      - '!all'
      - '!any'
      - devices

- name: Determine the partition ID for the swap_blk_device
  set_fact:
    swap_partition_id: "{{ '/dev/disk/by-id/' + ansible_facts.devices[swap_blk_device | basename].partitions | dict2items  | map(attribute='value.links.ids') | flatten | first() }}"

- name: swap | Initialize swap file
  command: mkswap -f {{ swap_partition_id }}
  become: true
  when: swapfile_register_create is changed

- name: swap | Enable swap file
  command: swapon {{ swap_partition_id }}
  become: true
  when: swapfile_register_create is changed

- name: swap | Manage swap file in /etc/fstab
  mount:
    src: "{{ swap_partition_id }}"
    name: "none"
    fstype: "swap"
    opts: "sw,nofail"
    dump: "0"
    passno: "0"
    state: "present"
  become: true
