# TODO: Logic to validate whether media exists is not working
#
#       Need to check for the prense of both the primary file names and the alternate file name
#
#  - name: install-by-unzip | Validating source files
#    stat:
#      path: "{{ swlib_path }}/{{ item.1 }}"
#    with_subelements:
#      - "{{ rdbms_software }}"
#      - altfiles
#    when: item.0.version == oracle_ver
#    register: f
#  - fail:
#      msg: "Cannot source media"
#    when: f.stat.isreg is not defined or not f.stat.isreg
#  - debug:
#      msg: "found source media"
#    when: f.stat.isreg is defined and f.stat.isreg