---
  - name: Copy database adjustment scripts to server
    template:
       src: "{{ item }}.j2"
       dest: "{{ swlib_unzip_path }}/{{ item }}"
       owner: "{{ oracle_user }}"
       group: "{{ oracle_group }}"
    with_items:
      - "{{ db_script_files }}"
    become: yes
    become_user: "{{ oracle_user }}"
    tags: db-adjustments

  - name: Run database adjustment scripts on server
    command: "sh {{ swlib_unzip_path }}/{{ item }}"
    with_items:
      - "{{ db_script_files }}"
    register: scripts_output
    ignore_errors: yes
    become: yes
    become_user: "{{ oracle_user }}"
    tags: db-adjustments

  - name: Database adjustment scripts output
    debug:
      msg: "{{ scripts_output }}"
      verbosity: 1
    tags: db-adjustments

  - name: Script cleanup on server
    file:
      path: "{{ swlib_unzip_path }}/{{ item }}"
      state: absent
    with_items:
      - "{{ db_script_files }}"
    become: yes
    become_user: "{{ oracle_user }}"
    tags: db-adjustments
