title: oracle-toolkit
description: Toolkit for installing and creating an initial database on Google Cloud Platform
remote_theme: pages-themes/cayman
plugins:
  - jekyll-remote-theme
markdown: kramdown
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
