# tasks file for roles/nfs-mount

- name: nfs | Install NFS mount utility
  become: true
  yum:
    name: nfs-utils
    state: present
    lock_timeout: 180
  when: ansible_os_family == "RedHat"

- name: nfs | Ensure rpcbind is running as configured.
  service:
    name: rpcbind
    state: started
    enabled: true
  when: ansible_os_family == "RedHat"

- name: nfs | Mount NFS share (swlib)
  become: true
  mount:
    fstype: nfs
    name: "{{ swlib_path }}"
    opts: "vers=4,_netdev,rsize=8192,wsize=8192,timeo=14,intr,user"
    src: "{{ swlib_mount_src }}"
    state: mounted

